### ISSUE TITLE
restart: code=101, text="BAD_SUPVISORS_STATE: Supvisors (state=INITIALIZATION) 

### ISSUE THREAD

**Issue by HieuTVGCH200824** [julien6387/supvisors#105]
Recently we've tried to implement 'supvisors' into our supervisord for easier management using the dashboard, we've encountered an error where the it keep stuck in 'INITIALIZATION' state. We are new to UNIX OS as well as the supervisor, hope that you can help us resolve this issue. Here is error we keep receiving upon re-synchronyzation.

2022-09-19 16:15:45,356;CRIT;SupervisorListener.on_tick: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/supvisors/listener.py", line 265, in on_tick
    self.pusher.send_tick_event(payload)
AttributeError: 'NoneType' object has no attribute 'send_tick_event'

2022-09-19 16:15:46,361;INFO;SupvisorsInstanceStatus.state: Supvisors=htv-virtual-machine is CHECKING
2022-09-19 16:15:46,362;WARN;InitializationState.next: synchro timed out
2022-09-19 16:15:46,362;INFO;SupvisorsInstanceStatus.state: Supvisors=htv-virtual-machine is CHECKING
2022-09-19 16:15:46,362;CRIT;SupervisorListener.on_remote_event: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/supvisors/listener.py", line 285, in on_remote_event
    self.unstack_event(event.data)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/listener.py", line 297, in unstack_event
    self.supvisors.fsm.on_tick_event(event_identifier, event_data)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/statemachine.py", line 493, in on_tick_event
    self.context.on_tick_event(identifier, event)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/context.py", line 429, in on_tick_event
    self.check_instance(status)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/context.py", line 632, in check_instance
    self.supvisors.zmq.pusher.send_check_instance(status.identifier)
AttributeError: 'NoneType' object has no attribute 'pusher'

2022-09-19 16:15:46,364;WARN;Context.on_authorization: failed to get auth status from Supvisors=htv-virtual-machine
2022-09-19 16:15:46,364;CRIT;Context.invalid: local Supvisors instance is either SILENT or inconsistent
2022-09-19 16:15:46,364;INFO;SupvisorsInstanceStatus.state: Supvisors=htv-virtual-machine is SILENT
2022-09-19 16:15:46,364;WARN;Context.on_authorization: failed to get auth status from Supvisors=htv-virtual-machine
2022-09-19 16:15:46,364;CRIT;Context.invalid: local Supvisors instance is either SILENT or inconsistent
2022-09-19 16:15:46,364;INFO;SupvisorsInstanceStatus.state: Supvisors=htv-virtual-machine is SILENT
2022-09-19 16:15:46,364;CRIT;SupervisorListener.on_remote_event: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/supvisors/listener.py", line 283, in on_remote_event
    self.authorization(event.data)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/listener.py", line 338, in authorization
    self.supvisors.fsm.on_authorization(identifier, authorized, master_identifier)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/statemachine.py", line 604, in on_authorization
    if self.context.on_authorization(identifier, authorized):
  File "/usr/local/lib/python3.10/dist-packages/supvisors/context.py", line 380, in on_authorization
    self.invalid(status)
  File "/usr/local/lib/python3.10/dist-packages/supvisors/context.py", line 198, in invalid
    self.supvisors.zmq.publisher.send_instance_status(status.serial())
AttributeError: 'NoneType' object has no attribute 'publisher'

**Comment by julien6387** [comment]
Hi Hieu,
My first guess is that PyZmq is not installed. It is a mandatory dependency of Supvisors, as stated in the project [README](https://github.com/julien6387/supvisors#dependencies).
I agree that it should be more obvious in the logs and I will raise an exception to the supervisor plugin factory.
Cheers,
Julien.

**Comment by HieuTVGCH200824** [comment]
I've already installed PyZMQ, at first I though it was a version conflic since you stated that it requires PyZMQ 20.0.0, an earlier version. I've tried to downgrade the version and this error still occurs.

**Comment by julien6387** [comment]
ok. could you please send me the full logs and your configuration files (supervisord.conf / XML rules) ?

**Comment by julien6387** [comment]
I've just noticed that you are using python 3.10
Supvisors has not been tested against this version.
The tests are performed with python versions between 3.6 and 3.9.
So this is a possible root cause, I'll check that.

**Comment by HieuTVGCH200824** [comment]
Somehow when recreating new supervisord.conf file the interface just work perfectly. My config file for testing is written as follow:

[inet_http_server]
port=:60000

[supervisord]
logfile=/tmp/supervisord.log
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false
umask=002

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://localhost:60000


;[rpcinterface:supvisors]
;supervisor.rpcinterface_factory = supvisors.plugin:make_supvisors_rpcinterface 
	

;[ctlplugin:supvisors]	
;supervisor.ctl_factory = supvisors.supvisorsctl:make_supvisors_controller_plugin

[rpcinterface:multivisor]
supervisor.rpcinterface_factory = multivisor.rpc:make_rpc_interface

[include]
files = /etc/supervisor/conf.d/*.ini

This problem does not exist when i'm testing other interfaces for supervisor.

**Comment by HieuTVGCH200824** [comment]
It seems like the problem laid in my config file was using unix socket based on the supervisor's configuration file while your interface require using localhost with a specified port.

**Comment by julien6387** [comment]
that's the first thing I checked in your configuration file but it looked ok.
Supvisors uses the Supervisor XML-RPC to communicate over multiple hosts so it indeed requires an internet socket, not a unix socket.
