### ISSUE TITLE
BAD_SUPVISORS_STATE (state=INITIALIZATION) while disabling

### ISSUE THREAD

**Issue by deeTEEcee** [julien6387/supvisors#113]
I'm not sure why this is happening. At the point where we disable here, I'm pretty confident the process is running and nothing else has happened to it (especially since this happens in a controlled test environment)

Another question is "should we even be concerned with operation state if we just want to disable and stop this process anyways?"

Probably not too useful but here's the stack trace as well:
```
/usr/local/lib/python3.7/site-packages/bson/__init__.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from bson import _cbson
/usr/local/lib/python3.7/site-packages/snapshottest/module.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
2023-06-05 16:42:08.940 [core] 97 ERROR - Error occurred when trying to stop supervisor process: some_process. Fault code 101: BAD_SUPVISORS_STATE: Supvisors (state=INITIALIZATION) not in state ['OPERATION'] to perform request
Traceback (most recent call last):
File "some_file.py", line 75, in manage_ftx
is_ok = proxy.supvisors.disable(FTX_PROCESS_NAME)
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
return self.__send(self.__name, args)
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 1452, in __request
verbose=self.__verbose
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 1154, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
return self.parse_response(resp)
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
return u.close()
File "/usr/local/lib/python3.7/xmlrpc/client.py", line 656, in close
raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 101: "BAD_SUPVISORS_STATE: Supvisors (state=INITIALIZATION) not in state ['OPERATION'] to perform request">
```

**Comment by julien6387** [comment]
As a general rule, I've put some restriction on the Supvisors control XML-RPCs before the OPERATIONAL state is reached.
The aim is to minimize the risk of interference on the automatic startup sequence eventually defined in the rules files.

And disabling a program is undoubtedly a source of interference.

That said, when Supvisors is configured with a single node context, the OPERATIONAL state is expected to be reached in less than 7-8 seconds after the supervisord process is started.
If not, there may be an issue with your Supvisors configuration. In that case, I would need the supervisor / supvisors log files and the configuration file as well.
