### ISSUE TITLE
when using username and passwd in inet_http_server, can't see the host page

### ISSUE THREAD

**Issue by westarest** [julien6387/supvisors#75]
2018-01-05 23:27:30,995 ERRO Web interface error:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supervisor/web.py", line 45, in more 
    response = self.callback()
  File "/usr/local/lib/python2.7/dist-packages/supervisor/web.py", line 162, in __call__
    body = self.render()
  File "/usr/local/lib/python2.7/dist-packages/supvisors/viewprocaddress.py", line 47, in render
    return ViewHandler.render(self)
  File "/usr/local/lib/python2.7/dist-packages/supvisors/viewhandler.py", line 74, in render
    self.write_contents(root)
  File "/usr/local/lib/python2.7/dist-packages/supvisors/viewprocaddress.py", line 75, in write_contents
    self.write_process_table(root)
  File "/usr/local/lib/python2.7/dist-packages/supvisors/viewprocaddress.py", line 93, in write_process_table
    for info in self.info_source.supervisor_rpc_interface.getAllProcessInfo():
  File "/usr/local/lib/python2.7/dist-packages/supvisors/infosource.py", line 48, in supervisor_rpc_interface
    self._supervisor_rpc_interface = self.httpserver.handlers[0].rpcinterface.supervisor
AttributeError: supervisor_auth_handler instance has no attribute 'rpcinterface'

**Comment by julien6387** [comment]
fixed in dev-0.2 branch
